libro/applications/biblioteca/urls.py
"""
Archivo de url de la app home
"""
from django.urls import path, re_path
from . import views

app_name="biblioteca_app"

# name="lista-autores" para acortar el nombre de la url "nueva-url"

# Si no pongo nada sera la url principal
urlpatterns = [
    path('', views.ListaAutores.as_view(), name="lista-autores"),
    path('libros-autor/<pk>/por-autor', views.ListaLibrosAutores.as_view(), name="lista-libros"),
    path('autor/add', views.addAutor.as_view(), name="autor-add"),
]

libro/applications/home/urls.py
"""
Archivo de url de la app home
"""
from django.urls import path, re_path
from . import views

app_name="home_app"

# name="index" para acortar el nombre de la url "nueva-url"

urlpatterns = [
    path('index', views.IndexView.as_view(), name="index"),
    path('libros', views.ListaLibros.as_view(), name="lista"),
]

libro/libro/urls.py
"""
Archivo principal de url
"""
from django.contrib import admin
from django.urls import path, re_path, include
# include sirve para poder llamar a las url

# En caso de error en el archivo de las url
# hay que reiniciar el server despues de arreglarlo

urlpatterns = [
    # Para que django incluya url del archivo urls.py de applications.home
    re_path(r'^',include('applications.home.urls')),
    re_path('admin/', admin.site.urls),
]

libro/applications/biblioteca/models.py
from django.db import models

# Create your models here.

# Creare un nuevo modelo, que es la representacion de una tabla
# que alamacenara cierto tipo de datos


# Que datos quiero pedir a autor y tipo de dato
# Nombres es el tag que el admin de django reconocera
# blank = true significa que no es obligatorio
class Autor(models.Model):
    nombre = models.CharField('Nombres',blank=False,max_length=80)
    nacionalidad = models.CharField(blank=True,max_length=100)

    # Valor por defecto que devolvera la tabla
    def __str__(self):
        return self.nombre

# Para crear en la bbdd hay que migrar
# python manage.py makemigrations (Revisa los cambios que hay)
# Y despues migrar (Los crea directamente en la bbdd)
# python manage.py migrate
# Despues hemos de ir a admin.py para acceder a las tablas 

libro/applications/home/models.py
from django.db import models

# Create your models here.

libro/applications/biblioteca/views.py
from django.shortcuts import render

# Create your views here.

libro/applications/home/views.py
from django.shortcuts import render

# Create your views here.

#Libreria de django para el ejemplo de la url "nueva-url"
from django.views.generic import(
    TemplateView,
    ListView,
)

class IndexView(TemplateView):
    # Una vista procesa los datos y renderiza el resultado en pantalla
    # Siempre nos pedira un template con el que trabajar
    # Un template es un archivo html **siempre**

    # Especificar con que template trabajamos
    template_name = "home/index.html"


class ListaLibros(ListView):
       template_name = 'home/lista.html'
       queryset = ['El quijote de la mancha','Codigo Limpio','Sombra del viento', 'Django2.0']
       # Con que nombre quiero manipular esta lista
       context_object_name = 'libros'

libro/templates/biblioteca/add-autor.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Agregar Autor</title>
  </head>
  <body>
    <h1>Agregar Autor</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="button">Guardar</button>
    </form>
  </body>
</html>
 

libro/templates/biblioteca/lista-autores.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Lista de Autores</title>
  </head>
  <body>
    <h1>Autores Registrados</h1>
    <table border="1">
      <thead>
        <th>ID</th>
        <th>Nombres</th>
        <th>Nacionalidad</th>
        <th>Accion</th>
      </thead>
      <tbody>
        {% for a in autores %}
        <tr>
          <td>{{a.id}}</td>
          <td>{{a.nombre}}</td>
          <td>{{a.nacionalidad}}</td>
          <td><a href="{% url 'biblioteca_app:lista-libros' a.id %}">VER LIBROS</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>

libro/templates/biblioteca/lista-libros.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Lista Libros por Autor</title>
  </head>
  <body>
    <h1>Lista libros autor</h1>
    <table border="1">
      <thead>
        <th>ID</th>
        <th>Titulo</th>
        <th>Autor</th>
      </thead>
      <tbody>
        {% for l in libros %}
        <tr>
          <td>{{l.id}}</td>
          <td>{{l.title}}</td>
          <td>{{l.autor}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>

libro/templates/home/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Index</h1>
  </body>
</html>

libro/templates/home/lista.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Lista de libros - vistas genericas</h1>

    <!-- Iteración para mostrar la lista de libros -->
    {% for l in libros %}
    <p>{{ l }}</p>
    {% endfor %}
  </body>
</html>